version: '3.8'

services:
  app:
    build: .
    container_name: elvtd_backend
    ports:
      - "5021:5021"
    env_file:
      - .env
    environment:
      - DB_DRIVER=${DOC_DB_DRIVER}
      - DB_HOST=${DOC_DB_HOST}
      - DB_PORT=${DOC_DB_PORT}
      - DB_NAME=${DOC_DB_NAME}
      - DB_USER=${DOC_DB_USER}
      - DB_PASSWORD=${DOC_DB_PASSWORD}
      - COPY_TOLERANCE_SECOND=${COPY_TOLERANCE_SECOND}
    depends_on:
      - database

  database:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: elvtd_mysql
    ports: 
      - "${DOC_DB_PORT}:3306"
    environment: 
      - MYSQL_ROOT_HOST=${DOC_DB_HOST}
      - MYSQL_USER=${DOC_DB_USER}
      - MYSQL_PASSWORD=${DOC_DB_PASSWORD}
      - MYSQL_DATABASE=${DOC_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DOC_DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql

volumes:
  database_mysql:
