name: 🚀 Deploy to Production Server

on:
  push:
    tags:
      - 'v*'   # contoh: v1.0.0, v1.2.3

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🔑 Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no root@65.108.60.88 "
            cd ~/elvtd-backend && \
            git fetch origin master && \
            git reset --hard origin/master && \
            chmod +x deploy.sh && \
            ./deploy.sh
          "
